'use strict';
/* eslint-disable */
const script = [
    {name: 'intro', story: '<p>There are few narratives that can so completely capture your senses that you find yourself quite literally pulled into it’s story. You were warned to take care while leafing through it’s pages, but took no heed. Now you find yourself suddenly in a small, provincial town where once your own home used to be. Instead of the familiar contemporary furnishings there are thatch roof houses and rustic peasants gawking at your unusual clothes. You have become the hero of your own story! You see to the right of you a slightly muddy road stretching off into the horizon of patchwork fields, and to the left the same road bends toward a wooded glen. Where do you go now?</p>',
    aButton: 'Take the forest path', bButton: 'Go down the road'},

    {name: 'A1', story: '<p>You decide to follow the forest path after seeing a sign indicating a city beyond it. How fortunate that the common language always seems to be English in these stories. Concerned murmurs among the villagers began to grow louder at your sudden presence, and you decide it’s best to leave in a hurry. The road is slick with mud, and the hay laid by the villagers does little to ease your trek. Once you reach the tree line you find that the canopy has provided cover from the elements and left the path more firm.</p><p>You walk for some time through the sun dappled forest until you come upon a fork in the road. One pathway looks very much like the other, and when you try to read the road marker planted between them, you find that the words had worn away with age. For several moments you ponder what to do, it would be dark before you could make it back to the village, and you had a fifty fifty chance of choosing the right path and making it to the city. Which way do you go?</p>',
    aButton: 'Left', bButton: 'Right', bg: 'forest', encounter: 'signpost'},

    {name: 'B1', story: '<p>You decide to follow the road through its surrounding, vast farmland. Concerned murmurs among the villagers had begun to grow louder at your sudden presence, and you decided it best to leave in a hurry. The mud on the road is just enough make your trek up and down the shallow hills that much more difficult, and leaves you breathing hard.  At each crest, you look ahead in hope of seeing a change in the landscape, or a potential destination that will lead you home.</p><p>At last, you come closer to a hill much taller than the rest.  In an older country, it might be called a mountain.  Though you can see its peak from the valley, its edges are sharp and steep.  Attempting to climb it would be futile, but when you squint against the sun flooding down over the ridiculously adorable little farms, you see a cave mouth peeking out from a fold in the hill.  Caves in fantasy stories are always a good idea, right?</p>',
    aButton:'Not a good idea. Keep walking', bButton: 'Approach the cave', bg: 'field'},
    
    {name: 'AA2', story: '<p>After much inner deliberation you decide to go on the left path, and thought at first you wonder about the other direction, you soon feel good about your decision as you see evidence of recent travel along the road.  As you continue, you begin to wonder about the people of this land, and what you will find when you surely reach the city lying ahead.  Sounds begin to reach you in the night, faintly.  You think it almost sounds like laughter, and voices, and hurry around the next corner.</p><p>But ahead, you see only the signs of a recent camp.  Whatever you heard has faded away on the breeze, and in front of you, you see only a large mirror laying on the ground amid disturbed earth and hoofprints. The edges are wrought with gilded filigree, and when you look into it you can see your reflection, and the inexplicable reflection of an ornate ceiling above you.</p>',
    aButton: 'Avoid the mirror and continue', bButton: 'Investigate it!', bg: 'forest', encounter: 'mirror'},

    {name: 'AB2', story: '<p>After much inner deliberation you decide on the right path and set off at a newly invigorated pace.  Though you hope to soon see signs of frequent travel, instead the path grows rougher and the forest more wild.  At first, you consider turning back, but stop yourself.  If there is magic somewhere in this world that could return you home, it is more likely to be in the deep forest than in the city.</p><p>As you continue further, the trees become larger and larger.  Along the old path, huge roots have pushed their way towards the center, like moss covered mountains crowding a river.  The trunks of these behemoths are wider than your arm span, and as you look up into the gathering dusk, you cannot tell where the canopy ends and the night sky begins.  Though the forest is covered in the hush of night, you have started to hear a quiet ticking noise, alien in the ancient world you’ve found yourself.  A deep sense of unease creeps up your spine as the ticking suddenly gets louder.  To your surprise it seems to be coming from a beautiful white rose, the only flower you’ve seen in the thickness of the forest.</p>',
    aButton: 'Pick the flower', bButton: 'Do not pick the flower', bg: 'forest', encounter: 'rose'},

    {name: 'BA2', story: '<p>You wisely continue on past the dark and ominous cave, hoping for a more inviting landmark. The sun continues to beat down on you, and the mud on the road is just enough make your trek up and down the shallow hills that much more difficult.  Finally, in the distance you see a copse of trees, and think it an excellent spot to rest.</p><p>As you approach, you see a series of gibbets hanging from the low branches of the tallest tree. They are mostly empty and rusted as they swing in the sun, but one contains an old man wrapped in a thin, graying blanket. When you draw nearer he rattles a dented, tin cup against the bars of his cage, and calls out to you. In a rasping voice he begs for a drink of water from a nearby stream to slack his terrible thirst.</p>',
    aButton: 'Try to free the old man', bButton: 'Take a detour to the stream', bg: 'field', encounter:'oldMan'},

    {name: 'BB2', story: '<p>You turn off your path and approach the opening of the cave. When you look back, and can’t find the road you were travelling on. A stone wall stares back at you that seemingly has arisen without your notice. You turn back around and enter the cave with much trepidation. The bats above you scream like rodent devils looking for fresh souls to devour. Your heart starts beating and you begin to run as the cave’s darkness envelops you, cold yet burning your psyche.</p><p>You run on into the darkness, your feet making surprisingly little noise as they pound within the empty dark.  You see nothing before you, and nothing behind, and your footsteps slowly become silent.  Almost in response, you begin to slow.  There is no sense of space anymore in the stillness around you.  Suddenly, like cracks in the very reality you walk in, two slits of bright light flash in front of you, and form into two blindingly bright door-like holes in the nothingness.  You know you must choose one, as the darkness begins to whisper across your skin.</p><p>Which door do you choose?</p>',
    aButton: 'Left door', bButton: 'Right door', bg: 'cave', encounter: 'doors'},

    {name: 'AAB3', story: '<p>You know the way these stories go.  Voices and mirrors do not plague travelers accidentally.  You approach the beautiful object on the road, stepping carefully.  You expect a surprise as you move toward it, but it only lies there, gleaming beautifully in the sun.</p><p>Picking up the mirror you can see the interior of this phantom room, and a large door in one of its walls. Leaning it up against a nearby tree, you gaze in and around the mirror room in puzzlement. Finally, you reach for the door knob, delicately carved in the likeness of climbing ivy, and turn it. The door swings open and you find yourself pulled into the room beyond. With dizzying speed you are thrown from the books pages and onto your own couch, and onto a very angry pet cat that yowls at how nearly it was crushed. The wind is knocked from your lungs, but you are home and alive. What a grand ending.</p>',
    bg: 'room', summary: 'You found your way home through a convenient magical mirror.'},

    {name: 'AAA3', story: '<p>Convenient magic mirrors do not interest you.  After your experience with the book, you seem to have developed an aversion to attractive and spooky objects.  You step past it, thinking again of the voices you hear, and the footsteps in the dust.  Where did those travelers go?  Your mind begins to wonder about what the cities of these land are like.  Perhaps there is wisdom there about your predicament.  Perhaps there are even other adventurers there that ignored the book’s warning and became trapped here.</p><p>You begin to hurry forward again, your mind racing with dreams of knowledge and community.  You follow the hoofprints through the trees, until you suddenly stop.  The hoofprints disappear before your eyes, as does the road.  Green grass emerges from under the vision, and looking around you, you see no evidence of the road, or any path.  Darkness has set in while you wandered.  The hair on your neck stands on end, and you feel a sinking in your stomach like you are being watched. Gurgling, retching sounds emanate from the darkness around you, and very soon your screams are lost in the empty night.</p>',  
    bg: 'death', summary: 'You died lost in the forest, probably eaten by a tree.'},

    {name: 'ABA3', story: '<p>The ticking of the flower is enchanting.  Its sound is so different from everything else around you, it begins to fill up your mind.  You walk toward the gleaming whiteness of it, wondering what it will feel like it your hands.  How wonderful it is, and how amazing it would be to bring such a thing home with you from this amazing world.</p><p>You bend and slowly reach your hand towards it, almost unconscious of the thorns at its base as you consider owning and keeping the beautiful thing.  You cup it at its base, the petals feeling cloud soft against your palm.  The ticking suddenly stops, as you pull it towards you, imagining the heavenly smell of such a rose.  At first, this is calming, and you think it must appreciate your touch, until the center of the flower opens, revealing rows upon rows of sharp and ragged teeth.  As entranced as you are, this is only momentarily confusing, before the entire flower opens wide and closes around your head.</p>',
    bg: 'death', summary: 'You were literally eaten by a flower, good job.'},

    {name: 'ABB3', story: '<p>The rose, so eerily clean and white in the darkness of the wood, and that wretched tick ticking, remind you of the dark and surreal nightmares of your childhood.  You back away from it, not even looking behind you, and come up against a surface.  You think it must be one of the sturdy trunks that have surrounded you, and you flatten against it, staring at the deadly rose as the ticking sounds louder and louder in your head.</p><p>Suddenly, the surface behind you gives way.  You try to spin around, or reach out, to grab at the tree you assume to be there, but find nothing under your hands.  You begin to fall, and the ticking thankfully begins to recede from your mind.  In fear, you shut your eyes tight again the spinning all around you, and hear a kind voice in your ear, whispering from nowhere into your mind, “I hate that flower, too."</p><p>With a bump and a jolt, you hit something soft, and your eyes fly open to see- what?  It looks exactly like your living room.  The movie you left on is still playing on your television, and a breeze from your open window brushes your face with a strong smell of your neighborhood.  You’re home.</p>',
    bg: 'room', summary: 'You chose the right side in an ancient flower rivalry, and were granted passage.'},

    {name: 'BAA3', story: '<p>Taking pity on this filthy, slightly dotty old man you are filled with a determination to set him free, as any good hero would. Picking up a sharp looking rock from the ground you poise it to strike the heavy metal padlock holding the cage’s tiny door closed. The prisoner within wails about his thirst and that you are wasting time on an impossible task.</p><p>The sound of stone on iron rang out loudly with each successive hit, and each time it seemed to vibrate more and more violently. Suddenly it began to jump and bounce seemingly of its own accord, it bends and grows before your eyes until it takes on the shape of a spiny metal gargoyle. The lock had been enchanted to attack whoever tried to open it without the proper key.</p><p>The creature set upon you, and without a weapon you were little match for the beast. You lay dead in the road while the old man continued to bang his cup against the bars of the cage in hopes of gaining an easement for his endless thirst.</p>',
    bg: 'death', summary: 'An enchanted cage gargoyle ripped you apart.', encounter: 'gargoyle'},

    {name: 'BAB3', story: '<p>You take the cup from this poor old man’s outstretched hand, and make off in the direction he points. After a half hour’s walk you see a large stream ahead running swiftly, it’s edges high on the bank from recent rain. You fill your cup and race back, careful not to spill your precious cargo. Upon your return the old man flails his arms madly in eagerness, and immediately gulps down the container’s contents the moment it touches his knobby fingers. Water dribbles down the side of his mouth and into his ragged beard, and after an exhalation of satisfaction wipes his face on the edge of the grimy blanket draped about his thin shoulders.</p><p>“Thank you for this kindness, Stranger. Even the smallest deed can have great consequences. I know you seek a way home, and I may be able to help you on your quest.”</p><p>With a snap of his fingers, the gibbet and the old vagrant vanished to be replaced by an elderly man in rich robes and a jaunty hat. He smiled sagely, and with another snap you feel yourself being pulled by an intangible force and are flung from the pages of your book onto the flimsy, Ikea coffee table. With a crash you lay among it’s splintered pieces stunned, but alive and home. What a grand ending.</p>',  
    bg: 'room', summary: 'You generously helped an old man, and he broke your coffee table.'},

    {name: 'BBA3', story: '<p>With no signs or differences to go off of, you quickly choose the left door, thinking any destination is better than the creeping dark encroaching from behind you.  You are wrong.</p><p>You step through blinding light, and at first it feels warm and welcoming, but suddenly the ground collapses beneath you and you fall into a new and deeper kind of darkness. You scream and feebly try to reach out and reach something solid, but there is nothing to touch, nothing to feel. You drop and drop, until eventually you give in and stop even flailing or trying to stop your descent.  Your soul spends eternity in this dark purgatory, never able to escape.</p>',
    bg: 'death', summary: 'You stumbled through a door into enternal darkness. Nice.'},

    {name: 'BBB3', story: '<p>Instinctively, you turn to the right and walk quickly into the light, eager to escape the cave and its driving darkness.  You are wrapped up and surrounded by brightness and warmth, a very sharp contrast to the cave you have just left.  With only a few steps forward the wrapping feeling begins to fade, and at first, you feel a pang of regret to lose it.  However, as you push on, you begin to recognize your surroundings.  Familiar objects begin to appear in your view, and you start to realize you are approaching a place that looks just like your bedroom.</p><p>Is this real? You hesitatingly sit down on your couch and contemplate everything that has come before. Was that real, or all just fantasy? You open the bedroom door and it leads to the hallway you’re used to. No need to check further. You sit back down on the couch and turn on a video game.  Much safer, you decide.</p>',
    bg: 'room', summary: 'You followed your instincts through a blissful door that only led to your bedroom.'},
];